<header class="hero">
  <div class="container">
    <hgroup>
      <h1>Get started with Cubex today!</h1>
    </hgroup>
    <aside class="text-center">
      <p>Run the following command to create your new project</p>
      <pre><code>composer create-project cubex/skeleton myproject</code></pre>
      <div class="hero-links">
        <a href="http://github.com/cubex"
           class="btn btn-warning" role="button"
           onclick="window.open(this.href); return false;">View On Github</a>
        <a href="/getting-started"
           class="btn btn-primary" role="button">Quick Start Guide</a>
        <a href="/docs"
           class="btn btn-success" role="button">Read the Docs</a>
      </div>
    </aside>
  </div>
</header>
