<br/>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">What is Cubex?</h3>
  </div>
  <div class="panel-body">
    <p>Cubex is an open source PHP framework designed around performance and
       simplicity. Cubex act as the glue for some great PHP packages, aiming to
       offer a consistent environment making development easier.</p>
  </div>
</div>

<div class="home-features">
  <div class="row">
    <div class="col-md-4">

      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">
            <span class="glyphicon glyphicon-fire"></span>
            Performance
          </h3>
        </div>
        <div class="panel-body">
          <p>Cubex is focused on optimising the speed of every request to ensure
             your
             code
             operates as fast as possible.</p>

          <p>Cubex is used within many high scale web applications and backends
             which
             demand performance to be at its best.</p>
        </div>
      </div>

    </div>
    <div class="col-md-4">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">
            <span class="glyphicon glyphicon-leaf"></span>
            Simplicity
          </h3>
        </div>
        <div class="panel-body">
          <p>There is no need to be writing boiler plate code these days.
             Cubex works to reducing the amount of code required to produce some
             amazing
             results, while supporting developers wishing to push the
             boundries.</p>
        </div>
      </div>

    </div>
    <div class="col-md-4">

      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">
            <span class="glyphicon glyphicon-flash"></span>
            Fully Tested
          </h3>
        </div>
        <div class="panel-body">
          <p>All code within cubex aims to have 100% code coverage, and test as
             many
             variations of user or developer input as possible.</p>

          <p>Test cases are constantly maintained with new functionality, and we
             aim
             to
             write tests for every bug fixed &amp; found, to ensure it doesn't
             ever
             come
             back.</p>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">
            <span class="glyphicon glyphicon-link"></span>
            Automatic &amp; Simple Routing
          </h3>
        </div>
        <div class="panel-body">
          <p>Just create your classes that extend the various available Cubex
             Kernels,
             and
             the hard work is done for you.</p>

          <p>Where you do need a slight variation on your routes, every layer is
             able
             to
             handle custom routing and redirects for you.</p>

        </div>
      </div>

    </div>
    <div class="col-md-4">

      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            Code To Conventions
          </h3>
        </div>
        <div class="panel-body">
          <p>By following various conventions in naming and structure, Cubex
             will
             take
             care of the rest for you.</p>

          <p>You no longer need to write routes, spend hours defining every
             parameter
             in
             your console commands.</p>
        </div>
      </div>

    </div>
    <div class="col-md-4">

      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">
            <span class="glyphicon glyphicon-tower"></span>
            Solid Foundations
          </h3>
        </div>
        <div class="panel-body">
          <p>Cubex where possible uses available packages from the community,
             with
             the
             HTTP foundation coming from Symfony and the IOC container coming
             from
             Laravel.</p>

          <p>Cubex aims to simply provide you with the wrapping ontop of great
             community
             php packages.</p>
        </div>
      </div>

    </div>
  </div>
</div>
