<div class="row-fluid">
  <div class="offset3 span6">

    <p>&nbsp;</p>
    <p>Copyright (c) 2012-<?php echo date("Y"); ?>, Just Develop It Ltd</p>
    <p>All rights reserved.</p>
    <p></p>
    <p>Redistribution and use in source and binary forms, with or without
       modification, are permitted provided that the following conditions are
       met:</p>
    <p></p>
    <p>Redistributions of source code must retain the above copyright notice, this
       list of conditions and the following disclaimer.</p>
    <p></p>
    <p>Redistributions in binary form must reproduce the above copyright notice,
       this list of conditions and the following disclaimer in the documentation
       and/or other materials provided with the distribution.</p>
    <p></p>
    <p>Neither the name of Just Develop It Ltd may be used to endorse or promote
       products derived from this software without specific prior written
       permission.</p>
    <p></p>
    <p>THIS SOFTWARE IS PROVIDED BY Just Develop It Ltd "AS IS" AND ANY EXPRESS OR
       IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
       MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
       EVENT SHALL Just Develop It Ltd BE LIABLE FOR ANY DIRECT, INDIRECT,
       INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
       LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
       OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
       LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
       NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
       EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</p>

  </div>
</div>
